Repository Book-Study-For-Developer/Frontend-Testing-For-Beginner, pull requests merged in 2025-02, with the labels that each got.

#2 [02/11] docs: 1 ~ 4장 내용 정리
  이우혁/chapter1/README.md
  이우혁/chapter2/README.md
  이우혁/chapter3/README.md
  이우혁/chapter4/README.md
Labels: 1회차, 발표자

#9 [02/11] docs: 1장 ~ 4장 내용 정리
  강은비/01. 테스트 목적과 장애물/README.md
  강은비/02. 테스트 방법과 테스트 전략/README.md
  강은비/03. 처음 시작하는 단위 테스트/README.md
  강은비/04. 목 객체/README.md
Labels: 1회차

#1 [02/11] docs: 1, 2, 3, 4장 내용 정리
  하현준/01. 테스트 목적과 장애물/README.md
  하현준/02. 테스트 방법과 테스트 전략/README.md
  하현준/03. 처음 시작하는 단위 테스트/README.md
  하현준/04. 목 객체/README.md
Labels: 1회차

#5 [02/11] docs: 1장 ~ 4장 내용 정리
  정소은/Chapter01/README.md
  정소은/Chapter02/README.md
  정소은/Chapter03/README.md
  정소은/Chapter03/image.png
  정소은/Chapter04/README.md
Labels: 1회차

#4 [02/11] docs: 1장 ~ 4장 내용 정리
  황낙준/1주차/README.md
  황낙준/2주차/README.md
  황낙준/3주차/README.md
  황낙준/4주차/README.md
Labels: 1회차

#10 [02/11] docs: 1장 ~ 4장 내용 정리
  이재혁/01. 테스트 목적과 장해물/README.md
  이재혁/02. 테스트 방법과 테스트 전략/README.md
  이재혁/03. 처음 시작하는 단위 테스트/README.md
  이재혁/04. 목 객체/README.md
Labels: 1회차

#6 [02/11] docs: 1장 ~ 4장 내용 정리
  박서영/01. 테스트 목적과 장애물/README.md
  박서영/02. 테스트 방법과 테스트 전략/README.md
  박서영/03. 처음 시작하는 단위 테스트/README.md
  박서영/03. 처음 시작하는 단위 테스트/images/image_0.png
  박서영/03. 처음 시작하는 단위 테스트/images/image_1.png
  박서영/03. 처음 시작하는 단위 테스트/images/image_2.png
  박서영/04. 목 객체/README.md
Labels: 1회차

#13 [02/11] docs: 1, 2, 3, 4장 내용 정리
  .DS_Store
  .gitignore
  이용훈/.DS_Store
  이용훈/Chapter 1/chapter1.md
  이용훈/Chapter 2/.DS_Store
  이용훈/Chapter 2/chapter2.md
  이용훈/Chapter 2/image.png
  이용훈/Chapter 3/chapter3.md
  이용훈/Chapter 4/chapter4.md
  이용훈/Chapter 4/image 1.png
  이용훈/Chapter 4/image 2.png
  이용훈/Chapter 4/image.png
Labels: 1회차, 발표자

#11 [02/11] docs: 1, 2, 3, 4장 내용 정리
  고석영/01. 테스트 목적과 장애물/README.md
  고석영/02. 테스트 방법과 테스트 전략/README.md
  고석영/02. 테스트 방법과 테스트 전략/testing-dorito.jpeg
  고석영/02. 테스트 방법과 테스트 전략/testing-ice-cream.png
  고석영/02. 테스트 방법과 테스트 전략/testing-pyramid.png
  고석영/02. 테스트 방법과 테스트 전략/testing-trophy.jpeg
  고석영/03. 처음 시작하는 단위 테스트/README.md
  고석영/04. 웹 API 목 객체 기초/README.md
  고석영/README.md
Labels: 1회차

#8 [02/11] docs: 1장 ~ 4장 내용 정리
  박상우/01. 테스트 목적과 장애물/README.md
  박상우/02.테스트 방법과 테스트 전략/README.md
  박상우/03. 처음 시작하는 단위 테스트/README.md
  박상우/04. 목 객체/README.md
  박상우/05. UI 컴포넌트 테스트/README.md
Labels: 1회차

#3 [02/11] docs: 1장 ~ 4장 내용 정리
  조명근/1주차/README.md
  조명근/2주차/README.md
Labels: 1회차

#7 [02/11] docs: 1장 ~ 4장 내용 정리
  정수지/chapter01.md
  정수지/chapter02.md
  정수지/chapter03.md
  정수지/chapter04.md
Labels: 1회차, 발표자

#12 [02/11] docs: 1, 2, 3, 4장 내용 정리
  .github/한재원/1. 테스트 목적과 장애물.md
  .github/한재원/2. 테스트 방법과 테스트 전략.md
  .github/한재원/3. 처음 시작하는 단위 테스트.md
  .github/한재원/4. 목 객체.md
Labels: 1회차

#21 [02/18] docs: 5장 내용 정리
  황낙준/01/README.md
  황낙준/02/README.md
  황낙준/03/README.md
  황낙준/04/README.md
  황낙준/05/README.md
  황낙준/05/multi-select-chip-group.spec.ts
  황낙준/05/phone-number-input.spec.ts
Labels: 2회차

#17 [02/18] docs: 5장 내용 정리
  강은비/05. UI 컴포넌트 테스트/README.md
Labels: 2회차, 발표자

#18 [02/18] docs: 5장 내용 정리
  정소은/Chapter05/README.md
Labels: 2회차, 발표자

#14 [02/18] docs: 5장 내용 정리
  하현준/05. UI 컴포넌트 테스트/README.md
Labels: 2회차

#15 [02/18] docs: 5장 내용 정리
  이우혁/chapter5/README.md
Labels: 2회차

#16 [02/18] docs: 5장 내용 정리
  이재혁/05. UI 컴포넌트 테스트/README.md
  이재혁/06. 커버리지 리포트 읽기/README.md
  이재혁/07. 웹 애플리케이션 통합 테스트/README.md
Labels: 2회차

#22 [02/18] docs: 5장 내용 정리
  박서영/05. UI 컴포넌트 테스트/README.md
Labels: 2회차

#24 [02/18] docs: 5장 내용 정리
  조명근/2주차/README.md
Labels: 2회차

#23 [02/18] docs: 5장 내용 정리
  고석영/05. UI 컴포넌트 테스트/README.md
  고석영/05. UI 컴포넌트 테스트/image.png
  고석영/README.md
Labels: 2회차

#25 [02/18] docs: 5장 내용 정리
  .DS_Store
  이용훈/.DS_Store
  이용훈/Chapter 2/.DS_Store
  이용훈/Chapter 4/chapter4.md
  이용훈/Chapter 4/image1.png
  이용훈/Chapter 4/image2.png
  이용훈/Chapter 5/chapter5.md
  이용훈/Chapter 5/image.png
  이용훈/Chapter 5/image1.png
  이용훈/Chapter 5/image2.png
  이용훈/Chapter 5/image3.png
  이용훈/Chapter 5/image4.png
  이용훈/Chapter 5/image5.png
Labels: 2회차

#26 [02/18] docs: 5장 내용 정리
  정수지/chapter01.md
  정수지/chapter02.md
  정수지/chapter05.md
Labels: 2회차, 발표자

#20 [02/18] docs: 5장 내용 정리
  박상우/05. UI 컴포넌트 테스트/README.md
Labels: 2회차
