Repository Book-Study-For-Developer/Frontend-Testing-For-Beginner, pull requests merged in 2025-03, with the labels that each got.

#33 [02/25] docs: 6장, 7장 내용 정리
  정소은/Chapter06/README.md
  정소은/Chapter06/image-1.png
  정소은/Chapter06/image.png
  정소은/Chapter07/README.md
Labels: 3회차

#27 [02/25] docs: 6장, 7장 내용 정리
  하현준/06. 커버리지 리포트 읽기/README.md
  하현준/07. 웹 애플리케이션 통합 테스트/README.md
Labels: 3회차, 발표자

#28 [02/25] docs: 6 ~ 7장 내용 정리
  이우혁/chapter6/README.md
  이우혁/chapter7/README.md
Labels: 3회차, 발표자

#29 [02/25] docs: 6장, 7장 내용 정리
  이재혁/06. 커버리지 리포트 읽기/README.md
  이재혁/07. 웹 애플리케이션 통합 테스트/README.md
Labels: 3회차, 발표자

#32 [02/25] docs: 6장, 7장 내용 정리
  조명근/3주차/README.md
Labels: 3회차

#31 [02/25] docs: 6장, 7장 내용 정리
  고석영/06. 커버리지 리포트 읽기/README.md
  고석영/06. 커버리지 리포트 읽기/image.png
  고석영/07. 웹 애플리케이션 통합 테스트/README.md
  고석영/README.md
Labels: 3회차

#35 [02/25] docs: 6장, 7장 내용 정리
  이용훈/Chapter 6/chapter6.md
  이용훈/Chapter 7/chapter7.md
Labels: 3회차

#30 [02/25] docs: 6장, 7장 내용 정리
  박서영/06. 커버리지 리포트 읽기/README.MD
  박서영/06. 커버리지 리포트 읽기/images/image_0.png
  박서영/06. 커버리지 리포트 읽기/images/image_1.png
  박서영/07. 웹 애플리케이션 통합 테스트/README.MD
Labels: 3회차

#37 [03/04] docs: 8장 내용 정리
  이우혁/chapter8/README.md
Labels: 4회차

#42 [03/04] docs: 8장 내용 정리
  이재혁/08. UI 컴포넌트 탐색기/README.md
Labels: 4회차

#36 [03/04] docs: 8장 내용 정리
  하현준/08. UI 컴포넌트 탐색기/README.md
Labels: 4회차, 발표자

#38 [03/04] docs: 8장 내용 정리
  정소은/Chapter08/README.md
Labels: 4회차

#43 [03/04] docs: 8장 내용 정리
  강은비/08. UI 컴포넌트 탐색기/README.md
Labels: 4회차, 발표자

#40 docs: 8장 내용 정리
  박상우/08. UI 컴포넌트 탐색기/README.md
Labels: 4회차

#45 [03/04] docs: 8장 내용 정리
  고석영/08. UI 컴포넌트 탐색기/README.md
  고석영/08. UI 컴포넌트 탐색기/image01.png
  고석영/08. UI 컴포넌트 탐색기/image02.png
  고석영/08. UI 컴포넌트 탐색기/image03.png
  고석영/README.md
Labels: 4회차

#41 docs: 8장 내용 정리
  조명근/4주차/READEME.md
Labels: 4회차, 발표자

#47 [03/11] docs: 9장 내용 정리
  하현준/09. 시각적 회귀 테스트/README.md
Labels: 5회차

#49 [03/11] docs: 9장 내용 정리
  고석영/09. 시각적 회귀 테스트/README.md
  고석영/09. 시각적 회귀 테스트/chromatic-review.png
  고석영/09. 시각적 회귀 테스트/chromatic-setup-a.png
  고석영/09. 시각적 회귀 테스트/chromatic-setup-b.png
  고석영/09. 시각적 회귀 테스트/github-actions.png
  고석영/09. 시각적 회귀 테스트/github-chromatic.png
  고석영/09. 시각적 회귀 테스트/github_flow.png
  고석영/09. 시각적 회귀 테스트/reg-suit.png
  고석영/09. 시각적 회귀 테스트/screenshot.png
  고석영/09. 시각적 회귀 테스트/storycap-cli.png
  고석영/09. 시각적 회귀 테스트/storycap-html.png
  고석영/README.md
Labels: 발표자, 5회차

#48 [03/11] docs: 9장 내용 정리
  이재혁/09. 시각적 회귀 테스트/README.md
Labels: 5회차

#46 [03/04] docs: 8장 내용 정리
  박서영/08. UI 컴포넌트 탐색기/README.MD
  박서영/08. UI 컴포넌트 탐색기/images/image_0.png
Labels: 4회차

#50 [03/11] docs: 9장 내용 정리
  박상우/09. 시각적 회귀 테스트/README.md
Labels: 5회차

#51 [03/11] docs: 9장 내용 정리
  이우혁/chapter10/README.md
  이우혁/chapter9/README.md
Labels: 5회차

#44 docs: 8장 내용 정리
  이용훈/Chapter 10/chapter10.md
  이용훈/Chapter 8/chapter8.md
Labels: 4회차

#54 [03/18] docs: 10장 내용 정리 6회차
  조명근/6주차/READEME.md
Labels: 6회차

#56 [03/18] docs: 10장 내용 정리
  정소은/Chapter10/README.md
Labels: 6회차

#53 [03/18] docs: 10장 내용 정리
  하현준/10. E2E 테스트/README.md
Labels: 6회차

#59 [03/18] docs: 10장 내용 정리 6회차
  이우혁/chapter10/README.md
Labels: 6회차

#55 [03/18] docs: 9~10장 내용 정리
  박서영/09. 시각적 회귀 테스트/README.MD
  박서영/10. E2E 테스트/README.MD
Labels: 6회차
