Repository Book-Study-For-Developer/Frontend-Testing-For-Beginner, pull requests merged in 2025-04, with the labels that each got.

#39 [03/04] docs: 6~8장 내용 정리
  정수지/chapter06.md
  정수지/chapter07.md
  정수지/chapter08.md
Labels: 3회차, 4회차

#57 [03/11] docs: 10장 내용 정리
  박상우/10. E2E 테스트/README.md
Labels: 발표자, 6회차

#58 [03/18] docs: 10장 내용 정리
  강은비/10. E2E 테스트/README.md
Labels: 6회차

#60 [03/18] docs: 10장 내용 정리
  고석영/10. E2E 테스트/README.md
  고석영/10. E2E 테스트/axe-playwright.png
  고석영/10. E2E 테스트/debugging-e2e-brower.png
  고석영/10. E2E 테스트/debugging-e2e-inspector.png
  고석영/10. E2E 테스트/seed-script.png
  고석영/README.md
Labels: 6회차
